---
title: "Channel report"
author: "Guillermo Diaz"
date: "`r Sys.Date()`"
output:
  pdf_document:
    toc: yes
    toc_depth: '3'
  html_document:
    code_folding: hide
    toc: yes
    toc_float: yes
    toc_align: left
    toc_depth: 3
    theme: united
params:
  my_channel: La 1
  date: !r format(Sys.Date(), "%d %B %Y")
---

```{r setup}
#| include = FALSE
knitr::opts_chunk$set(
	echo = TRUE,
	message = FALSE,
	warning = FALSE
)
```

#### Updated: `r params$date`
#### Analysis of `r params$my_channel`



```{r Load TDT data}
#| include = FALSE
library(dplyr)
library(readr)
library(lubridate)
library(stringr)

data <- read.csv("https://raw.githubusercontent.com/GuilleDiaz7/Automatic-Web-Scraping-of-Spanish-TDT-Films/main/data/pelis_tv_hoy.csv", fileEncoding = 'UTF-8')
```

```{r Clean the TDT data}
data <- data %>% 
  select(1:8) %>% 
  mutate(
  genre = replace(genre, genre == "Suspense / Thriller", "Suspense"),
  genre = replace(genre, genre == "Documentales", "Documental"),
  genre = replace(genre, genre == "Ciencia ficción", "SyFy"),
  genre = replace(genre, genre == "Infantil/Familiar", "Infantil"),
  date_time = as_datetime(date_time)
  ) %>% 
  dplyr::rename(
        Date = date_time,
    Channel = channel,
    "Spanish title" = sp_title,
    "Original title" = original_title,
    Year = year,
    Genre = genre,
    Country = country,
    Length = length
  )
```

# `r params$my_channel` channel report


```{r Add weekday}



df <- data %>% 
  mutate("Weekday" = weekdays.Date(Date, abbreviate = F)) %>% 
  relocate("Weekday", .after = Date) %>% 
  transmute(
    Date = Date,
    "Weekday" = case_when(
      str_detect(iconv(Weekday, to='ASCII//TRANSLIT'), regex("lunes|martes|miercoles|jueves", ignore_case = T)) ~ "Laboral",
      str_detect(iconv(Weekday, to='ASCII//TRANSLIT'), regex("viernes|sabado|domingo", ignore_case = T)) ~ "Finde"
      ),
    Channel = Channel,
    `Spanish title` = `Spanish title`,
    Length = Length,
    Year = Year,
    Genre = Genre,
    Country = Country
  )
```

## When are films broadcasted in `r params$my_channel`?


```{r}
#| include = FALSE
df %>%
  group_by(Date = as.Date(Date), Channel) %>% 
  summarise(Movies = n())
```


```{r}
library(gghighlight)

df %>% 
  group_by(Date = as.Date(Date), Channel) %>% 
  summarise(Movies = n()) %>% 
  ggplot(aes(x = Date, y = Movies,  col = Channel)) +
  geom_line() +
  gghighlight(Channel == params$my_channel) + 
  theme_classic() +
  scale_y_log10()

  
```


